
### 
POST http://localhost:8080/public/proveedor-register
Content-Type: application/json

{
  "User": {
    "email": "qweda@qwer.com",
    "password": "password123",
    "role": "proveedor"
  },
  "businessName": "Tieweplo",
  "contactEmail": "com",
  "contactPhone": "70012345"
}

### 
POST http://localhost:8080/public/login
Content-Type: application/json

{
"email": "cliente1@ejemplo.com",
"password": "password123"
}


### 
POST http://localhost:8080/public/client
Content-Type: application/json

{
  "User": {
    "email": "cliente1@ejemplo.com",
    "password": "password123",
    "role": "cliente"
  },
  "name": "Juan Perez",
  "contactEmail": "juan.contacto@ejemplo.com",
  "contactPhone": "999888777",
  "age": 30
}


###
POST http://localhost:8080/public/chat
Content-Type: application/json

{
  "question": "¿Cómo puedo cuidar mi salud alimenticia?"
}