
### 
POST http://localhost:8080/public/client
Content-Type: application/json

{
  "User": {
    "email": "juan@juan.com",
    "password": "juan",
    "role": "Cliente"
  },
  "Name": "Tieweplo",
  "contactEmail": "tiewe@ejemplo.com",
  "contactPhone": "70012345",
  "age": 30,
  "bloodType": "O+",
  "preExistingCondition": "Ninguna"
}

### 
POST http://localhost:8080/public/login
Content-Type: application/json

{
"email": "juan@juan.com",
"password": "juan"
}


### 
POST http://localhost:8080/public/client
Content-Type: application/json

{
  "User": {
    "email": "cliente1@ejemplo.com",
    "password": "password123",
    "role": "cliente"
  },
  "name": "Juan Perez",
  "contactEmail": "juan.contacto@ejemplo.com",
  "contactPhone": "999888777",
  "age": 30
}


###
POST http://localhost:8080/public/chat
Content-Type: application/json

{
  "question": "estas funcionando? solo devuelveme un si o no"
}

